name: br
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gozssky/tidb
          ref: ebs-based-br
      - name: Setup tag
        run: |
          git tag v6.2.0-alpha
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl && mv kubectl br/pkg/hack/
      - name: Build
        run: make build_br
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: gozssky/br
          tags: |
            type=raw,value=v{{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value=latest
      # The v2 version of docker/build-push-action uses Docker Buildx to build.
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.br
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Image digest
        run:
          echo ${{ steps.docker_build.outputs.digest }}